export enum StatusPedido {
    PENDENTE = 'PENDENTE',
    CONFIRMADO = 'CONFIRMADO',
    EM_PREPARO = 'EM_PREPARO',
    SAIU_PARA_ENTREGA = 'SAIU_PARA_ENTREGA',
    ENTREGUE = 'ENTREGUE',
    CANCELADO = 'CANCELADO'
}