
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Carrinho` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Carrinho
 * 
 */
export type CarrinhoModel = runtime.Types.Result.DefaultSelection<Prisma.$CarrinhoPayload>

export type AggregateCarrinho = {
  _count: CarrinhoCountAggregateOutputType | null
  _avg: CarrinhoAvgAggregateOutputType | null
  _sum: CarrinhoSumAggregateOutputType | null
  _min: CarrinhoMinAggregateOutputType | null
  _max: CarrinhoMaxAggregateOutputType | null
}

export type CarrinhoAvgAggregateOutputType = {
  id: number | null
  clienteId: number | null
}

export type CarrinhoSumAggregateOutputType = {
  id: number | null
  clienteId: number | null
}

export type CarrinhoMinAggregateOutputType = {
  id: number | null
  clienteId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CarrinhoMaxAggregateOutputType = {
  id: number | null
  clienteId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CarrinhoCountAggregateOutputType = {
  id: number
  clienteId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CarrinhoAvgAggregateInputType = {
  id?: true
  clienteId?: true
}

export type CarrinhoSumAggregateInputType = {
  id?: true
  clienteId?: true
}

export type CarrinhoMinAggregateInputType = {
  id?: true
  clienteId?: true
  createdAt?: true
  updatedAt?: true
}

export type CarrinhoMaxAggregateInputType = {
  id?: true
  clienteId?: true
  createdAt?: true
  updatedAt?: true
}

export type CarrinhoCountAggregateInputType = {
  id?: true
  clienteId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CarrinhoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Carrinho to aggregate.
   */
  where?: Prisma.CarrinhoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Carrinhos to fetch.
   */
  orderBy?: Prisma.CarrinhoOrderByWithRelationInput | Prisma.CarrinhoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CarrinhoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Carrinhos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Carrinhos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Carrinhos
  **/
  _count?: true | CarrinhoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CarrinhoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CarrinhoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CarrinhoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CarrinhoMaxAggregateInputType
}

export type GetCarrinhoAggregateType<T extends CarrinhoAggregateArgs> = {
      [P in keyof T & keyof AggregateCarrinho]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCarrinho[P]>
    : Prisma.GetScalarType<T[P], AggregateCarrinho[P]>
}




export type CarrinhoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CarrinhoWhereInput
  orderBy?: Prisma.CarrinhoOrderByWithAggregationInput | Prisma.CarrinhoOrderByWithAggregationInput[]
  by: Prisma.CarrinhoScalarFieldEnum[] | Prisma.CarrinhoScalarFieldEnum
  having?: Prisma.CarrinhoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CarrinhoCountAggregateInputType | true
  _avg?: CarrinhoAvgAggregateInputType
  _sum?: CarrinhoSumAggregateInputType
  _min?: CarrinhoMinAggregateInputType
  _max?: CarrinhoMaxAggregateInputType
}

export type CarrinhoGroupByOutputType = {
  id: number
  clienteId: number
  createdAt: Date
  updatedAt: Date
  _count: CarrinhoCountAggregateOutputType | null
  _avg: CarrinhoAvgAggregateOutputType | null
  _sum: CarrinhoSumAggregateOutputType | null
  _min: CarrinhoMinAggregateOutputType | null
  _max: CarrinhoMaxAggregateOutputType | null
}

export type GetCarrinhoGroupByPayload<T extends CarrinhoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CarrinhoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CarrinhoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CarrinhoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CarrinhoGroupByOutputType[P]>
      }
    >
  >



export type CarrinhoWhereInput = {
  AND?: Prisma.CarrinhoWhereInput | Prisma.CarrinhoWhereInput[]
  OR?: Prisma.CarrinhoWhereInput[]
  NOT?: Prisma.CarrinhoWhereInput | Prisma.CarrinhoWhereInput[]
  id?: Prisma.IntFilter<"Carrinho"> | number
  clienteId?: Prisma.IntFilter<"Carrinho"> | number
  createdAt?: Prisma.DateTimeFilter<"Carrinho"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Carrinho"> | Date | string
  cliente?: Prisma.XOR<Prisma.ClienteScalarRelationFilter, Prisma.ClienteWhereInput>
  itens?: Prisma.ItemCarrinhoListRelationFilter
}

export type CarrinhoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  cliente?: Prisma.ClienteOrderByWithRelationInput
  itens?: Prisma.ItemCarrinhoOrderByRelationAggregateInput
}

export type CarrinhoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  clienteId?: number
  AND?: Prisma.CarrinhoWhereInput | Prisma.CarrinhoWhereInput[]
  OR?: Prisma.CarrinhoWhereInput[]
  NOT?: Prisma.CarrinhoWhereInput | Prisma.CarrinhoWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"Carrinho"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Carrinho"> | Date | string
  cliente?: Prisma.XOR<Prisma.ClienteScalarRelationFilter, Prisma.ClienteWhereInput>
  itens?: Prisma.ItemCarrinhoListRelationFilter
}, "id" | "clienteId">

export type CarrinhoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CarrinhoCountOrderByAggregateInput
  _avg?: Prisma.CarrinhoAvgOrderByAggregateInput
  _max?: Prisma.CarrinhoMaxOrderByAggregateInput
  _min?: Prisma.CarrinhoMinOrderByAggregateInput
  _sum?: Prisma.CarrinhoSumOrderByAggregateInput
}

export type CarrinhoScalarWhereWithAggregatesInput = {
  AND?: Prisma.CarrinhoScalarWhereWithAggregatesInput | Prisma.CarrinhoScalarWhereWithAggregatesInput[]
  OR?: Prisma.CarrinhoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CarrinhoScalarWhereWithAggregatesInput | Prisma.CarrinhoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Carrinho"> | number
  clienteId?: Prisma.IntWithAggregatesFilter<"Carrinho"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Carrinho"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Carrinho"> | Date | string
}

export type CarrinhoCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  cliente: Prisma.ClienteCreateNestedOneWithoutCarrinhoInput
  itens?: Prisma.ItemCarrinhoCreateNestedManyWithoutCarrinhoInput
}

export type CarrinhoUncheckedCreateInput = {
  id?: number
  clienteId: number
  createdAt?: Date | string
  updatedAt?: Date | string
  itens?: Prisma.ItemCarrinhoUncheckedCreateNestedManyWithoutCarrinhoInput
}

export type CarrinhoUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cliente?: Prisma.ClienteUpdateOneRequiredWithoutCarrinhoNestedInput
  itens?: Prisma.ItemCarrinhoUpdateManyWithoutCarrinhoNestedInput
}

export type CarrinhoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  clienteId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  itens?: Prisma.ItemCarrinhoUncheckedUpdateManyWithoutCarrinhoNestedInput
}

export type CarrinhoCreateManyInput = {
  id?: number
  clienteId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CarrinhoUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CarrinhoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  clienteId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CarrinhoNullableScalarRelationFilter = {
  is?: Prisma.CarrinhoWhereInput | null
  isNot?: Prisma.CarrinhoWhereInput | null
}

export type CarrinhoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CarrinhoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
}

export type CarrinhoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CarrinhoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CarrinhoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
}

export type CarrinhoScalarRelationFilter = {
  is?: Prisma.CarrinhoWhereInput
  isNot?: Prisma.CarrinhoWhereInput
}

export type CarrinhoCreateNestedOneWithoutClienteInput = {
  create?: Prisma.XOR<Prisma.CarrinhoCreateWithoutClienteInput, Prisma.CarrinhoUncheckedCreateWithoutClienteInput>
  connectOrCreate?: Prisma.CarrinhoCreateOrConnectWithoutClienteInput
  connect?: Prisma.CarrinhoWhereUniqueInput
}

export type CarrinhoUncheckedCreateNestedOneWithoutClienteInput = {
  create?: Prisma.XOR<Prisma.CarrinhoCreateWithoutClienteInput, Prisma.CarrinhoUncheckedCreateWithoutClienteInput>
  connectOrCreate?: Prisma.CarrinhoCreateOrConnectWithoutClienteInput
  connect?: Prisma.CarrinhoWhereUniqueInput
}

export type CarrinhoUpdateOneWithoutClienteNestedInput = {
  create?: Prisma.XOR<Prisma.CarrinhoCreateWithoutClienteInput, Prisma.CarrinhoUncheckedCreateWithoutClienteInput>
  connectOrCreate?: Prisma.CarrinhoCreateOrConnectWithoutClienteInput
  upsert?: Prisma.CarrinhoUpsertWithoutClienteInput
  disconnect?: Prisma.CarrinhoWhereInput | boolean
  delete?: Prisma.CarrinhoWhereInput | boolean
  connect?: Prisma.CarrinhoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CarrinhoUpdateToOneWithWhereWithoutClienteInput, Prisma.CarrinhoUpdateWithoutClienteInput>, Prisma.CarrinhoUncheckedUpdateWithoutClienteInput>
}

export type CarrinhoUncheckedUpdateOneWithoutClienteNestedInput = {
  create?: Prisma.XOR<Prisma.CarrinhoCreateWithoutClienteInput, Prisma.CarrinhoUncheckedCreateWithoutClienteInput>
  connectOrCreate?: Prisma.CarrinhoCreateOrConnectWithoutClienteInput
  upsert?: Prisma.CarrinhoUpsertWithoutClienteInput
  disconnect?: Prisma.CarrinhoWhereInput | boolean
  delete?: Prisma.CarrinhoWhereInput | boolean
  connect?: Prisma.CarrinhoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CarrinhoUpdateToOneWithWhereWithoutClienteInput, Prisma.CarrinhoUpdateWithoutClienteInput>, Prisma.CarrinhoUncheckedUpdateWithoutClienteInput>
}

export type CarrinhoCreateNestedOneWithoutItensInput = {
  create?: Prisma.XOR<Prisma.CarrinhoCreateWithoutItensInput, Prisma.CarrinhoUncheckedCreateWithoutItensInput>
  connectOrCreate?: Prisma.CarrinhoCreateOrConnectWithoutItensInput
  connect?: Prisma.CarrinhoWhereUniqueInput
}

export type CarrinhoUpdateOneRequiredWithoutItensNestedInput = {
  create?: Prisma.XOR<Prisma.CarrinhoCreateWithoutItensInput, Prisma.CarrinhoUncheckedCreateWithoutItensInput>
  connectOrCreate?: Prisma.CarrinhoCreateOrConnectWithoutItensInput
  upsert?: Prisma.CarrinhoUpsertWithoutItensInput
  connect?: Prisma.CarrinhoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CarrinhoUpdateToOneWithWhereWithoutItensInput, Prisma.CarrinhoUpdateWithoutItensInput>, Prisma.CarrinhoUncheckedUpdateWithoutItensInput>
}

export type CarrinhoCreateWithoutClienteInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  itens?: Prisma.ItemCarrinhoCreateNestedManyWithoutCarrinhoInput
}

export type CarrinhoUncheckedCreateWithoutClienteInput = {
  id?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  itens?: Prisma.ItemCarrinhoUncheckedCreateNestedManyWithoutCarrinhoInput
}

export type CarrinhoCreateOrConnectWithoutClienteInput = {
  where: Prisma.CarrinhoWhereUniqueInput
  create: Prisma.XOR<Prisma.CarrinhoCreateWithoutClienteInput, Prisma.CarrinhoUncheckedCreateWithoutClienteInput>
}

export type CarrinhoUpsertWithoutClienteInput = {
  update: Prisma.XOR<Prisma.CarrinhoUpdateWithoutClienteInput, Prisma.CarrinhoUncheckedUpdateWithoutClienteInput>
  create: Prisma.XOR<Prisma.CarrinhoCreateWithoutClienteInput, Prisma.CarrinhoUncheckedCreateWithoutClienteInput>
  where?: Prisma.CarrinhoWhereInput
}

export type CarrinhoUpdateToOneWithWhereWithoutClienteInput = {
  where?: Prisma.CarrinhoWhereInput
  data: Prisma.XOR<Prisma.CarrinhoUpdateWithoutClienteInput, Prisma.CarrinhoUncheckedUpdateWithoutClienteInput>
}

export type CarrinhoUpdateWithoutClienteInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  itens?: Prisma.ItemCarrinhoUpdateManyWithoutCarrinhoNestedInput
}

export type CarrinhoUncheckedUpdateWithoutClienteInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  itens?: Prisma.ItemCarrinhoUncheckedUpdateManyWithoutCarrinhoNestedInput
}

export type CarrinhoCreateWithoutItensInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  cliente: Prisma.ClienteCreateNestedOneWithoutCarrinhoInput
}

export type CarrinhoUncheckedCreateWithoutItensInput = {
  id?: number
  clienteId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CarrinhoCreateOrConnectWithoutItensInput = {
  where: Prisma.CarrinhoWhereUniqueInput
  create: Prisma.XOR<Prisma.CarrinhoCreateWithoutItensInput, Prisma.CarrinhoUncheckedCreateWithoutItensInput>
}

export type CarrinhoUpsertWithoutItensInput = {
  update: Prisma.XOR<Prisma.CarrinhoUpdateWithoutItensInput, Prisma.CarrinhoUncheckedUpdateWithoutItensInput>
  create: Prisma.XOR<Prisma.CarrinhoCreateWithoutItensInput, Prisma.CarrinhoUncheckedCreateWithoutItensInput>
  where?: Prisma.CarrinhoWhereInput
}

export type CarrinhoUpdateToOneWithWhereWithoutItensInput = {
  where?: Prisma.CarrinhoWhereInput
  data: Prisma.XOR<Prisma.CarrinhoUpdateWithoutItensInput, Prisma.CarrinhoUncheckedUpdateWithoutItensInput>
}

export type CarrinhoUpdateWithoutItensInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cliente?: Prisma.ClienteUpdateOneRequiredWithoutCarrinhoNestedInput
}

export type CarrinhoUncheckedUpdateWithoutItensInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  clienteId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type CarrinhoCountOutputType
 */

export type CarrinhoCountOutputType = {
  itens: number
}

export type CarrinhoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  itens?: boolean | CarrinhoCountOutputTypeCountItensArgs
}

/**
 * CarrinhoCountOutputType without action
 */
export type CarrinhoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CarrinhoCountOutputType
   */
  select?: Prisma.CarrinhoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CarrinhoCountOutputType without action
 */
export type CarrinhoCountOutputTypeCountItensArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ItemCarrinhoWhereInput
}


export type CarrinhoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clienteId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cliente?: boolean | Prisma.ClienteDefaultArgs<ExtArgs>
  itens?: boolean | Prisma.Carrinho$itensArgs<ExtArgs>
  _count?: boolean | Prisma.CarrinhoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["carrinho"]>

export type CarrinhoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clienteId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cliente?: boolean | Prisma.ClienteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["carrinho"]>

export type CarrinhoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clienteId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cliente?: boolean | Prisma.ClienteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["carrinho"]>

export type CarrinhoSelectScalar = {
  id?: boolean
  clienteId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CarrinhoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "clienteId" | "createdAt" | "updatedAt", ExtArgs["result"]["carrinho"]>
export type CarrinhoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cliente?: boolean | Prisma.ClienteDefaultArgs<ExtArgs>
  itens?: boolean | Prisma.Carrinho$itensArgs<ExtArgs>
  _count?: boolean | Prisma.CarrinhoCountOutputTypeDefaultArgs<ExtArgs>
}
export type CarrinhoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cliente?: boolean | Prisma.ClienteDefaultArgs<ExtArgs>
}
export type CarrinhoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cliente?: boolean | Prisma.ClienteDefaultArgs<ExtArgs>
}

export type $CarrinhoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Carrinho"
  objects: {
    cliente: Prisma.$ClientePayload<ExtArgs>
    itens: Prisma.$ItemCarrinhoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    clienteId: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["carrinho"]>
  composites: {}
}

export type CarrinhoGetPayload<S extends boolean | null | undefined | CarrinhoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload, S>

export type CarrinhoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CarrinhoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CarrinhoCountAggregateInputType | true
  }

export interface CarrinhoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Carrinho'], meta: { name: 'Carrinho' } }
  /**
   * Find zero or one Carrinho that matches the filter.
   * @param {CarrinhoFindUniqueArgs} args - Arguments to find a Carrinho
   * @example
   * // Get one Carrinho
   * const carrinho = await prisma.carrinho.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CarrinhoFindUniqueArgs>(args: Prisma.SelectSubset<T, CarrinhoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CarrinhoClient<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Carrinho that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CarrinhoFindUniqueOrThrowArgs} args - Arguments to find a Carrinho
   * @example
   * // Get one Carrinho
   * const carrinho = await prisma.carrinho.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CarrinhoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CarrinhoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CarrinhoClient<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Carrinho that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CarrinhoFindFirstArgs} args - Arguments to find a Carrinho
   * @example
   * // Get one Carrinho
   * const carrinho = await prisma.carrinho.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CarrinhoFindFirstArgs>(args?: Prisma.SelectSubset<T, CarrinhoFindFirstArgs<ExtArgs>>): Prisma.Prisma__CarrinhoClient<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Carrinho that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CarrinhoFindFirstOrThrowArgs} args - Arguments to find a Carrinho
   * @example
   * // Get one Carrinho
   * const carrinho = await prisma.carrinho.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CarrinhoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CarrinhoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CarrinhoClient<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Carrinhos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CarrinhoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Carrinhos
   * const carrinhos = await prisma.carrinho.findMany()
   * 
   * // Get first 10 Carrinhos
   * const carrinhos = await prisma.carrinho.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const carrinhoWithIdOnly = await prisma.carrinho.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CarrinhoFindManyArgs>(args?: Prisma.SelectSubset<T, CarrinhoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Carrinho.
   * @param {CarrinhoCreateArgs} args - Arguments to create a Carrinho.
   * @example
   * // Create one Carrinho
   * const Carrinho = await prisma.carrinho.create({
   *   data: {
   *     // ... data to create a Carrinho
   *   }
   * })
   * 
   */
  create<T extends CarrinhoCreateArgs>(args: Prisma.SelectSubset<T, CarrinhoCreateArgs<ExtArgs>>): Prisma.Prisma__CarrinhoClient<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Carrinhos.
   * @param {CarrinhoCreateManyArgs} args - Arguments to create many Carrinhos.
   * @example
   * // Create many Carrinhos
   * const carrinho = await prisma.carrinho.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CarrinhoCreateManyArgs>(args?: Prisma.SelectSubset<T, CarrinhoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Carrinhos and returns the data saved in the database.
   * @param {CarrinhoCreateManyAndReturnArgs} args - Arguments to create many Carrinhos.
   * @example
   * // Create many Carrinhos
   * const carrinho = await prisma.carrinho.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Carrinhos and only return the `id`
   * const carrinhoWithIdOnly = await prisma.carrinho.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CarrinhoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CarrinhoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Carrinho.
   * @param {CarrinhoDeleteArgs} args - Arguments to delete one Carrinho.
   * @example
   * // Delete one Carrinho
   * const Carrinho = await prisma.carrinho.delete({
   *   where: {
   *     // ... filter to delete one Carrinho
   *   }
   * })
   * 
   */
  delete<T extends CarrinhoDeleteArgs>(args: Prisma.SelectSubset<T, CarrinhoDeleteArgs<ExtArgs>>): Prisma.Prisma__CarrinhoClient<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Carrinho.
   * @param {CarrinhoUpdateArgs} args - Arguments to update one Carrinho.
   * @example
   * // Update one Carrinho
   * const carrinho = await prisma.carrinho.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CarrinhoUpdateArgs>(args: Prisma.SelectSubset<T, CarrinhoUpdateArgs<ExtArgs>>): Prisma.Prisma__CarrinhoClient<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Carrinhos.
   * @param {CarrinhoDeleteManyArgs} args - Arguments to filter Carrinhos to delete.
   * @example
   * // Delete a few Carrinhos
   * const { count } = await prisma.carrinho.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CarrinhoDeleteManyArgs>(args?: Prisma.SelectSubset<T, CarrinhoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Carrinhos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CarrinhoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Carrinhos
   * const carrinho = await prisma.carrinho.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CarrinhoUpdateManyArgs>(args: Prisma.SelectSubset<T, CarrinhoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Carrinhos and returns the data updated in the database.
   * @param {CarrinhoUpdateManyAndReturnArgs} args - Arguments to update many Carrinhos.
   * @example
   * // Update many Carrinhos
   * const carrinho = await prisma.carrinho.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Carrinhos and only return the `id`
   * const carrinhoWithIdOnly = await prisma.carrinho.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CarrinhoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CarrinhoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Carrinho.
   * @param {CarrinhoUpsertArgs} args - Arguments to update or create a Carrinho.
   * @example
   * // Update or create a Carrinho
   * const carrinho = await prisma.carrinho.upsert({
   *   create: {
   *     // ... data to create a Carrinho
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Carrinho we want to update
   *   }
   * })
   */
  upsert<T extends CarrinhoUpsertArgs>(args: Prisma.SelectSubset<T, CarrinhoUpsertArgs<ExtArgs>>): Prisma.Prisma__CarrinhoClient<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Carrinhos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CarrinhoCountArgs} args - Arguments to filter Carrinhos to count.
   * @example
   * // Count the number of Carrinhos
   * const count = await prisma.carrinho.count({
   *   where: {
   *     // ... the filter for the Carrinhos we want to count
   *   }
   * })
  **/
  count<T extends CarrinhoCountArgs>(
    args?: Prisma.Subset<T, CarrinhoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CarrinhoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Carrinho.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CarrinhoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CarrinhoAggregateArgs>(args: Prisma.Subset<T, CarrinhoAggregateArgs>): Prisma.PrismaPromise<GetCarrinhoAggregateType<T>>

  /**
   * Group by Carrinho.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CarrinhoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CarrinhoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CarrinhoGroupByArgs['orderBy'] }
      : { orderBy?: CarrinhoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CarrinhoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCarrinhoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Carrinho model
 */
readonly fields: CarrinhoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Carrinho.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CarrinhoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  cliente<T extends Prisma.ClienteDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClienteDefaultArgs<ExtArgs>>): Prisma.Prisma__ClienteClient<runtime.Types.Result.GetResult<Prisma.$ClientePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  itens<T extends Prisma.Carrinho$itensArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Carrinho$itensArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Carrinho model
 */
export interface CarrinhoFieldRefs {
  readonly id: Prisma.FieldRef<"Carrinho", 'Int'>
  readonly clienteId: Prisma.FieldRef<"Carrinho", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Carrinho", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Carrinho", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Carrinho findUnique
 */
export type CarrinhoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoInclude<ExtArgs> | null
  /**
   * Filter, which Carrinho to fetch.
   */
  where: Prisma.CarrinhoWhereUniqueInput
}

/**
 * Carrinho findUniqueOrThrow
 */
export type CarrinhoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoInclude<ExtArgs> | null
  /**
   * Filter, which Carrinho to fetch.
   */
  where: Prisma.CarrinhoWhereUniqueInput
}

/**
 * Carrinho findFirst
 */
export type CarrinhoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoInclude<ExtArgs> | null
  /**
   * Filter, which Carrinho to fetch.
   */
  where?: Prisma.CarrinhoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Carrinhos to fetch.
   */
  orderBy?: Prisma.CarrinhoOrderByWithRelationInput | Prisma.CarrinhoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Carrinhos.
   */
  cursor?: Prisma.CarrinhoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Carrinhos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Carrinhos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Carrinhos.
   */
  distinct?: Prisma.CarrinhoScalarFieldEnum | Prisma.CarrinhoScalarFieldEnum[]
}

/**
 * Carrinho findFirstOrThrow
 */
export type CarrinhoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoInclude<ExtArgs> | null
  /**
   * Filter, which Carrinho to fetch.
   */
  where?: Prisma.CarrinhoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Carrinhos to fetch.
   */
  orderBy?: Prisma.CarrinhoOrderByWithRelationInput | Prisma.CarrinhoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Carrinhos.
   */
  cursor?: Prisma.CarrinhoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Carrinhos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Carrinhos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Carrinhos.
   */
  distinct?: Prisma.CarrinhoScalarFieldEnum | Prisma.CarrinhoScalarFieldEnum[]
}

/**
 * Carrinho findMany
 */
export type CarrinhoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoInclude<ExtArgs> | null
  /**
   * Filter, which Carrinhos to fetch.
   */
  where?: Prisma.CarrinhoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Carrinhos to fetch.
   */
  orderBy?: Prisma.CarrinhoOrderByWithRelationInput | Prisma.CarrinhoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Carrinhos.
   */
  cursor?: Prisma.CarrinhoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Carrinhos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Carrinhos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Carrinhos.
   */
  distinct?: Prisma.CarrinhoScalarFieldEnum | Prisma.CarrinhoScalarFieldEnum[]
}

/**
 * Carrinho create
 */
export type CarrinhoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoInclude<ExtArgs> | null
  /**
   * The data needed to create a Carrinho.
   */
  data: Prisma.XOR<Prisma.CarrinhoCreateInput, Prisma.CarrinhoUncheckedCreateInput>
}

/**
 * Carrinho createMany
 */
export type CarrinhoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Carrinhos.
   */
  data: Prisma.CarrinhoCreateManyInput | Prisma.CarrinhoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Carrinho createManyAndReturn
 */
export type CarrinhoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * The data used to create many Carrinhos.
   */
  data: Prisma.CarrinhoCreateManyInput | Prisma.CarrinhoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Carrinho update
 */
export type CarrinhoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoInclude<ExtArgs> | null
  /**
   * The data needed to update a Carrinho.
   */
  data: Prisma.XOR<Prisma.CarrinhoUpdateInput, Prisma.CarrinhoUncheckedUpdateInput>
  /**
   * Choose, which Carrinho to update.
   */
  where: Prisma.CarrinhoWhereUniqueInput
}

/**
 * Carrinho updateMany
 */
export type CarrinhoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Carrinhos.
   */
  data: Prisma.XOR<Prisma.CarrinhoUpdateManyMutationInput, Prisma.CarrinhoUncheckedUpdateManyInput>
  /**
   * Filter which Carrinhos to update
   */
  where?: Prisma.CarrinhoWhereInput
  /**
   * Limit how many Carrinhos to update.
   */
  limit?: number
}

/**
 * Carrinho updateManyAndReturn
 */
export type CarrinhoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * The data used to update Carrinhos.
   */
  data: Prisma.XOR<Prisma.CarrinhoUpdateManyMutationInput, Prisma.CarrinhoUncheckedUpdateManyInput>
  /**
   * Filter which Carrinhos to update
   */
  where?: Prisma.CarrinhoWhereInput
  /**
   * Limit how many Carrinhos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Carrinho upsert
 */
export type CarrinhoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoInclude<ExtArgs> | null
  /**
   * The filter to search for the Carrinho to update in case it exists.
   */
  where: Prisma.CarrinhoWhereUniqueInput
  /**
   * In case the Carrinho found by the `where` argument doesn't exist, create a new Carrinho with this data.
   */
  create: Prisma.XOR<Prisma.CarrinhoCreateInput, Prisma.CarrinhoUncheckedCreateInput>
  /**
   * In case the Carrinho was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CarrinhoUpdateInput, Prisma.CarrinhoUncheckedUpdateInput>
}

/**
 * Carrinho delete
 */
export type CarrinhoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoInclude<ExtArgs> | null
  /**
   * Filter which Carrinho to delete.
   */
  where: Prisma.CarrinhoWhereUniqueInput
}

/**
 * Carrinho deleteMany
 */
export type CarrinhoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Carrinhos to delete
   */
  where?: Prisma.CarrinhoWhereInput
  /**
   * Limit how many Carrinhos to delete.
   */
  limit?: number
}

/**
 * Carrinho.itens
 */
export type Carrinho$itensArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
  where?: Prisma.ItemCarrinhoWhereInput
  orderBy?: Prisma.ItemCarrinhoOrderByWithRelationInput | Prisma.ItemCarrinhoOrderByWithRelationInput[]
  cursor?: Prisma.ItemCarrinhoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ItemCarrinhoScalarFieldEnum | Prisma.ItemCarrinhoScalarFieldEnum[]
}

/**
 * Carrinho without action
 */
export type CarrinhoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Carrinho
   */
  select?: Prisma.CarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Carrinho
   */
  omit?: Prisma.CarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CarrinhoInclude<ExtArgs> | null
}
