
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ItemCarrinho` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ItemCarrinho
 * 
 */
export type ItemCarrinhoModel = runtime.Types.Result.DefaultSelection<Prisma.$ItemCarrinhoPayload>

export type AggregateItemCarrinho = {
  _count: ItemCarrinhoCountAggregateOutputType | null
  _avg: ItemCarrinhoAvgAggregateOutputType | null
  _sum: ItemCarrinhoSumAggregateOutputType | null
  _min: ItemCarrinhoMinAggregateOutputType | null
  _max: ItemCarrinhoMaxAggregateOutputType | null
}

export type ItemCarrinhoAvgAggregateOutputType = {
  id: number | null
  carrinhoId: number | null
  produtoId: number | null
  quantidade: number | null
  precoUnitario: runtime.Decimal | null
}

export type ItemCarrinhoSumAggregateOutputType = {
  id: number | null
  carrinhoId: number | null
  produtoId: number | null
  quantidade: number | null
  precoUnitario: runtime.Decimal | null
}

export type ItemCarrinhoMinAggregateOutputType = {
  id: number | null
  carrinhoId: number | null
  produtoId: number | null
  quantidade: number | null
  precoUnitario: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ItemCarrinhoMaxAggregateOutputType = {
  id: number | null
  carrinhoId: number | null
  produtoId: number | null
  quantidade: number | null
  precoUnitario: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ItemCarrinhoCountAggregateOutputType = {
  id: number
  carrinhoId: number
  produtoId: number
  quantidade: number
  precoUnitario: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ItemCarrinhoAvgAggregateInputType = {
  id?: true
  carrinhoId?: true
  produtoId?: true
  quantidade?: true
  precoUnitario?: true
}

export type ItemCarrinhoSumAggregateInputType = {
  id?: true
  carrinhoId?: true
  produtoId?: true
  quantidade?: true
  precoUnitario?: true
}

export type ItemCarrinhoMinAggregateInputType = {
  id?: true
  carrinhoId?: true
  produtoId?: true
  quantidade?: true
  precoUnitario?: true
  createdAt?: true
  updatedAt?: true
}

export type ItemCarrinhoMaxAggregateInputType = {
  id?: true
  carrinhoId?: true
  produtoId?: true
  quantidade?: true
  precoUnitario?: true
  createdAt?: true
  updatedAt?: true
}

export type ItemCarrinhoCountAggregateInputType = {
  id?: true
  carrinhoId?: true
  produtoId?: true
  quantidade?: true
  precoUnitario?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ItemCarrinhoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ItemCarrinho to aggregate.
   */
  where?: Prisma.ItemCarrinhoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemCarrinhos to fetch.
   */
  orderBy?: Prisma.ItemCarrinhoOrderByWithRelationInput | Prisma.ItemCarrinhoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ItemCarrinhoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemCarrinhos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemCarrinhos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ItemCarrinhos
  **/
  _count?: true | ItemCarrinhoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ItemCarrinhoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ItemCarrinhoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ItemCarrinhoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ItemCarrinhoMaxAggregateInputType
}

export type GetItemCarrinhoAggregateType<T extends ItemCarrinhoAggregateArgs> = {
      [P in keyof T & keyof AggregateItemCarrinho]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateItemCarrinho[P]>
    : Prisma.GetScalarType<T[P], AggregateItemCarrinho[P]>
}




export type ItemCarrinhoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ItemCarrinhoWhereInput
  orderBy?: Prisma.ItemCarrinhoOrderByWithAggregationInput | Prisma.ItemCarrinhoOrderByWithAggregationInput[]
  by: Prisma.ItemCarrinhoScalarFieldEnum[] | Prisma.ItemCarrinhoScalarFieldEnum
  having?: Prisma.ItemCarrinhoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ItemCarrinhoCountAggregateInputType | true
  _avg?: ItemCarrinhoAvgAggregateInputType
  _sum?: ItemCarrinhoSumAggregateInputType
  _min?: ItemCarrinhoMinAggregateInputType
  _max?: ItemCarrinhoMaxAggregateInputType
}

export type ItemCarrinhoGroupByOutputType = {
  id: number
  carrinhoId: number
  produtoId: number
  quantidade: number
  precoUnitario: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: ItemCarrinhoCountAggregateOutputType | null
  _avg: ItemCarrinhoAvgAggregateOutputType | null
  _sum: ItemCarrinhoSumAggregateOutputType | null
  _min: ItemCarrinhoMinAggregateOutputType | null
  _max: ItemCarrinhoMaxAggregateOutputType | null
}

export type GetItemCarrinhoGroupByPayload<T extends ItemCarrinhoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ItemCarrinhoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ItemCarrinhoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ItemCarrinhoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ItemCarrinhoGroupByOutputType[P]>
      }
    >
  >



export type ItemCarrinhoWhereInput = {
  AND?: Prisma.ItemCarrinhoWhereInput | Prisma.ItemCarrinhoWhereInput[]
  OR?: Prisma.ItemCarrinhoWhereInput[]
  NOT?: Prisma.ItemCarrinhoWhereInput | Prisma.ItemCarrinhoWhereInput[]
  id?: Prisma.IntFilter<"ItemCarrinho"> | number
  carrinhoId?: Prisma.IntFilter<"ItemCarrinho"> | number
  produtoId?: Prisma.IntFilter<"ItemCarrinho"> | number
  quantidade?: Prisma.IntFilter<"ItemCarrinho"> | number
  precoUnitario?: Prisma.DecimalFilter<"ItemCarrinho"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"ItemCarrinho"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ItemCarrinho"> | Date | string
  carrinho?: Prisma.XOR<Prisma.CarrinhoScalarRelationFilter, Prisma.CarrinhoWhereInput>
  produto?: Prisma.XOR<Prisma.ProdutoScalarRelationFilter, Prisma.ProdutoWhereInput>
}

export type ItemCarrinhoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  carrinhoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnitario?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  carrinho?: Prisma.CarrinhoOrderByWithRelationInput
  produto?: Prisma.ProdutoOrderByWithRelationInput
}

export type ItemCarrinhoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  carrinhoId_produtoId?: Prisma.ItemCarrinhoCarrinhoIdProdutoIdCompoundUniqueInput
  AND?: Prisma.ItemCarrinhoWhereInput | Prisma.ItemCarrinhoWhereInput[]
  OR?: Prisma.ItemCarrinhoWhereInput[]
  NOT?: Prisma.ItemCarrinhoWhereInput | Prisma.ItemCarrinhoWhereInput[]
  carrinhoId?: Prisma.IntFilter<"ItemCarrinho"> | number
  produtoId?: Prisma.IntFilter<"ItemCarrinho"> | number
  quantidade?: Prisma.IntFilter<"ItemCarrinho"> | number
  precoUnitario?: Prisma.DecimalFilter<"ItemCarrinho"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"ItemCarrinho"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ItemCarrinho"> | Date | string
  carrinho?: Prisma.XOR<Prisma.CarrinhoScalarRelationFilter, Prisma.CarrinhoWhereInput>
  produto?: Prisma.XOR<Prisma.ProdutoScalarRelationFilter, Prisma.ProdutoWhereInput>
}, "id" | "carrinhoId_produtoId">

export type ItemCarrinhoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  carrinhoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnitario?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ItemCarrinhoCountOrderByAggregateInput
  _avg?: Prisma.ItemCarrinhoAvgOrderByAggregateInput
  _max?: Prisma.ItemCarrinhoMaxOrderByAggregateInput
  _min?: Prisma.ItemCarrinhoMinOrderByAggregateInput
  _sum?: Prisma.ItemCarrinhoSumOrderByAggregateInput
}

export type ItemCarrinhoScalarWhereWithAggregatesInput = {
  AND?: Prisma.ItemCarrinhoScalarWhereWithAggregatesInput | Prisma.ItemCarrinhoScalarWhereWithAggregatesInput[]
  OR?: Prisma.ItemCarrinhoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ItemCarrinhoScalarWhereWithAggregatesInput | Prisma.ItemCarrinhoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ItemCarrinho"> | number
  carrinhoId?: Prisma.IntWithAggregatesFilter<"ItemCarrinho"> | number
  produtoId?: Prisma.IntWithAggregatesFilter<"ItemCarrinho"> | number
  quantidade?: Prisma.IntWithAggregatesFilter<"ItemCarrinho"> | number
  precoUnitario?: Prisma.DecimalWithAggregatesFilter<"ItemCarrinho"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ItemCarrinho"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ItemCarrinho"> | Date | string
}

export type ItemCarrinhoCreateInput = {
  quantidade?: number
  precoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  carrinho: Prisma.CarrinhoCreateNestedOneWithoutItensInput
  produto: Prisma.ProdutoCreateNestedOneWithoutItensCarrinhoInput
}

export type ItemCarrinhoUncheckedCreateInput = {
  id?: number
  carrinhoId: number
  produtoId: number
  quantidade?: number
  precoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemCarrinhoUpdateInput = {
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  carrinho?: Prisma.CarrinhoUpdateOneRequiredWithoutItensNestedInput
  produto?: Prisma.ProdutoUpdateOneRequiredWithoutItensCarrinhoNestedInput
}

export type ItemCarrinhoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  carrinhoId?: Prisma.IntFieldUpdateOperationsInput | number
  produtoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemCarrinhoCreateManyInput = {
  id?: number
  carrinhoId: number
  produtoId: number
  quantidade?: number
  precoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemCarrinhoUpdateManyMutationInput = {
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemCarrinhoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  carrinhoId?: Prisma.IntFieldUpdateOperationsInput | number
  produtoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemCarrinhoListRelationFilter = {
  every?: Prisma.ItemCarrinhoWhereInput
  some?: Prisma.ItemCarrinhoWhereInput
  none?: Prisma.ItemCarrinhoWhereInput
}

export type ItemCarrinhoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ItemCarrinhoCarrinhoIdProdutoIdCompoundUniqueInput = {
  carrinhoId: number
  produtoId: number
}

export type ItemCarrinhoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  carrinhoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnitario?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ItemCarrinhoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  carrinhoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnitario?: Prisma.SortOrder
}

export type ItemCarrinhoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  carrinhoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnitario?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ItemCarrinhoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  carrinhoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnitario?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ItemCarrinhoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  carrinhoId?: Prisma.SortOrder
  produtoId?: Prisma.SortOrder
  quantidade?: Prisma.SortOrder
  precoUnitario?: Prisma.SortOrder
}

export type ItemCarrinhoCreateNestedManyWithoutProdutoInput = {
  create?: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutProdutoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutProdutoInput> | Prisma.ItemCarrinhoCreateWithoutProdutoInput[] | Prisma.ItemCarrinhoUncheckedCreateWithoutProdutoInput[]
  connectOrCreate?: Prisma.ItemCarrinhoCreateOrConnectWithoutProdutoInput | Prisma.ItemCarrinhoCreateOrConnectWithoutProdutoInput[]
  createMany?: Prisma.ItemCarrinhoCreateManyProdutoInputEnvelope
  connect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
}

export type ItemCarrinhoUncheckedCreateNestedManyWithoutProdutoInput = {
  create?: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutProdutoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutProdutoInput> | Prisma.ItemCarrinhoCreateWithoutProdutoInput[] | Prisma.ItemCarrinhoUncheckedCreateWithoutProdutoInput[]
  connectOrCreate?: Prisma.ItemCarrinhoCreateOrConnectWithoutProdutoInput | Prisma.ItemCarrinhoCreateOrConnectWithoutProdutoInput[]
  createMany?: Prisma.ItemCarrinhoCreateManyProdutoInputEnvelope
  connect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
}

export type ItemCarrinhoUpdateManyWithoutProdutoNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutProdutoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutProdutoInput> | Prisma.ItemCarrinhoCreateWithoutProdutoInput[] | Prisma.ItemCarrinhoUncheckedCreateWithoutProdutoInput[]
  connectOrCreate?: Prisma.ItemCarrinhoCreateOrConnectWithoutProdutoInput | Prisma.ItemCarrinhoCreateOrConnectWithoutProdutoInput[]
  upsert?: Prisma.ItemCarrinhoUpsertWithWhereUniqueWithoutProdutoInput | Prisma.ItemCarrinhoUpsertWithWhereUniqueWithoutProdutoInput[]
  createMany?: Prisma.ItemCarrinhoCreateManyProdutoInputEnvelope
  set?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  disconnect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  delete?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  connect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  update?: Prisma.ItemCarrinhoUpdateWithWhereUniqueWithoutProdutoInput | Prisma.ItemCarrinhoUpdateWithWhereUniqueWithoutProdutoInput[]
  updateMany?: Prisma.ItemCarrinhoUpdateManyWithWhereWithoutProdutoInput | Prisma.ItemCarrinhoUpdateManyWithWhereWithoutProdutoInput[]
  deleteMany?: Prisma.ItemCarrinhoScalarWhereInput | Prisma.ItemCarrinhoScalarWhereInput[]
}

export type ItemCarrinhoUncheckedUpdateManyWithoutProdutoNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutProdutoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutProdutoInput> | Prisma.ItemCarrinhoCreateWithoutProdutoInput[] | Prisma.ItemCarrinhoUncheckedCreateWithoutProdutoInput[]
  connectOrCreate?: Prisma.ItemCarrinhoCreateOrConnectWithoutProdutoInput | Prisma.ItemCarrinhoCreateOrConnectWithoutProdutoInput[]
  upsert?: Prisma.ItemCarrinhoUpsertWithWhereUniqueWithoutProdutoInput | Prisma.ItemCarrinhoUpsertWithWhereUniqueWithoutProdutoInput[]
  createMany?: Prisma.ItemCarrinhoCreateManyProdutoInputEnvelope
  set?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  disconnect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  delete?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  connect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  update?: Prisma.ItemCarrinhoUpdateWithWhereUniqueWithoutProdutoInput | Prisma.ItemCarrinhoUpdateWithWhereUniqueWithoutProdutoInput[]
  updateMany?: Prisma.ItemCarrinhoUpdateManyWithWhereWithoutProdutoInput | Prisma.ItemCarrinhoUpdateManyWithWhereWithoutProdutoInput[]
  deleteMany?: Prisma.ItemCarrinhoScalarWhereInput | Prisma.ItemCarrinhoScalarWhereInput[]
}

export type ItemCarrinhoCreateNestedManyWithoutCarrinhoInput = {
  create?: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutCarrinhoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutCarrinhoInput> | Prisma.ItemCarrinhoCreateWithoutCarrinhoInput[] | Prisma.ItemCarrinhoUncheckedCreateWithoutCarrinhoInput[]
  connectOrCreate?: Prisma.ItemCarrinhoCreateOrConnectWithoutCarrinhoInput | Prisma.ItemCarrinhoCreateOrConnectWithoutCarrinhoInput[]
  createMany?: Prisma.ItemCarrinhoCreateManyCarrinhoInputEnvelope
  connect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
}

export type ItemCarrinhoUncheckedCreateNestedManyWithoutCarrinhoInput = {
  create?: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutCarrinhoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutCarrinhoInput> | Prisma.ItemCarrinhoCreateWithoutCarrinhoInput[] | Prisma.ItemCarrinhoUncheckedCreateWithoutCarrinhoInput[]
  connectOrCreate?: Prisma.ItemCarrinhoCreateOrConnectWithoutCarrinhoInput | Prisma.ItemCarrinhoCreateOrConnectWithoutCarrinhoInput[]
  createMany?: Prisma.ItemCarrinhoCreateManyCarrinhoInputEnvelope
  connect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
}

export type ItemCarrinhoUpdateManyWithoutCarrinhoNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutCarrinhoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutCarrinhoInput> | Prisma.ItemCarrinhoCreateWithoutCarrinhoInput[] | Prisma.ItemCarrinhoUncheckedCreateWithoutCarrinhoInput[]
  connectOrCreate?: Prisma.ItemCarrinhoCreateOrConnectWithoutCarrinhoInput | Prisma.ItemCarrinhoCreateOrConnectWithoutCarrinhoInput[]
  upsert?: Prisma.ItemCarrinhoUpsertWithWhereUniqueWithoutCarrinhoInput | Prisma.ItemCarrinhoUpsertWithWhereUniqueWithoutCarrinhoInput[]
  createMany?: Prisma.ItemCarrinhoCreateManyCarrinhoInputEnvelope
  set?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  disconnect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  delete?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  connect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  update?: Prisma.ItemCarrinhoUpdateWithWhereUniqueWithoutCarrinhoInput | Prisma.ItemCarrinhoUpdateWithWhereUniqueWithoutCarrinhoInput[]
  updateMany?: Prisma.ItemCarrinhoUpdateManyWithWhereWithoutCarrinhoInput | Prisma.ItemCarrinhoUpdateManyWithWhereWithoutCarrinhoInput[]
  deleteMany?: Prisma.ItemCarrinhoScalarWhereInput | Prisma.ItemCarrinhoScalarWhereInput[]
}

export type ItemCarrinhoUncheckedUpdateManyWithoutCarrinhoNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutCarrinhoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutCarrinhoInput> | Prisma.ItemCarrinhoCreateWithoutCarrinhoInput[] | Prisma.ItemCarrinhoUncheckedCreateWithoutCarrinhoInput[]
  connectOrCreate?: Prisma.ItemCarrinhoCreateOrConnectWithoutCarrinhoInput | Prisma.ItemCarrinhoCreateOrConnectWithoutCarrinhoInput[]
  upsert?: Prisma.ItemCarrinhoUpsertWithWhereUniqueWithoutCarrinhoInput | Prisma.ItemCarrinhoUpsertWithWhereUniqueWithoutCarrinhoInput[]
  createMany?: Prisma.ItemCarrinhoCreateManyCarrinhoInputEnvelope
  set?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  disconnect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  delete?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  connect?: Prisma.ItemCarrinhoWhereUniqueInput | Prisma.ItemCarrinhoWhereUniqueInput[]
  update?: Prisma.ItemCarrinhoUpdateWithWhereUniqueWithoutCarrinhoInput | Prisma.ItemCarrinhoUpdateWithWhereUniqueWithoutCarrinhoInput[]
  updateMany?: Prisma.ItemCarrinhoUpdateManyWithWhereWithoutCarrinhoInput | Prisma.ItemCarrinhoUpdateManyWithWhereWithoutCarrinhoInput[]
  deleteMany?: Prisma.ItemCarrinhoScalarWhereInput | Prisma.ItemCarrinhoScalarWhereInput[]
}

export type ItemCarrinhoCreateWithoutProdutoInput = {
  quantidade?: number
  precoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  carrinho: Prisma.CarrinhoCreateNestedOneWithoutItensInput
}

export type ItemCarrinhoUncheckedCreateWithoutProdutoInput = {
  id?: number
  carrinhoId: number
  quantidade?: number
  precoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemCarrinhoCreateOrConnectWithoutProdutoInput = {
  where: Prisma.ItemCarrinhoWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutProdutoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutProdutoInput>
}

export type ItemCarrinhoCreateManyProdutoInputEnvelope = {
  data: Prisma.ItemCarrinhoCreateManyProdutoInput | Prisma.ItemCarrinhoCreateManyProdutoInput[]
  skipDuplicates?: boolean
}

export type ItemCarrinhoUpsertWithWhereUniqueWithoutProdutoInput = {
  where: Prisma.ItemCarrinhoWhereUniqueInput
  update: Prisma.XOR<Prisma.ItemCarrinhoUpdateWithoutProdutoInput, Prisma.ItemCarrinhoUncheckedUpdateWithoutProdutoInput>
  create: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutProdutoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutProdutoInput>
}

export type ItemCarrinhoUpdateWithWhereUniqueWithoutProdutoInput = {
  where: Prisma.ItemCarrinhoWhereUniqueInput
  data: Prisma.XOR<Prisma.ItemCarrinhoUpdateWithoutProdutoInput, Prisma.ItemCarrinhoUncheckedUpdateWithoutProdutoInput>
}

export type ItemCarrinhoUpdateManyWithWhereWithoutProdutoInput = {
  where: Prisma.ItemCarrinhoScalarWhereInput
  data: Prisma.XOR<Prisma.ItemCarrinhoUpdateManyMutationInput, Prisma.ItemCarrinhoUncheckedUpdateManyWithoutProdutoInput>
}

export type ItemCarrinhoScalarWhereInput = {
  AND?: Prisma.ItemCarrinhoScalarWhereInput | Prisma.ItemCarrinhoScalarWhereInput[]
  OR?: Prisma.ItemCarrinhoScalarWhereInput[]
  NOT?: Prisma.ItemCarrinhoScalarWhereInput | Prisma.ItemCarrinhoScalarWhereInput[]
  id?: Prisma.IntFilter<"ItemCarrinho"> | number
  carrinhoId?: Prisma.IntFilter<"ItemCarrinho"> | number
  produtoId?: Prisma.IntFilter<"ItemCarrinho"> | number
  quantidade?: Prisma.IntFilter<"ItemCarrinho"> | number
  precoUnitario?: Prisma.DecimalFilter<"ItemCarrinho"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"ItemCarrinho"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ItemCarrinho"> | Date | string
}

export type ItemCarrinhoCreateWithoutCarrinhoInput = {
  quantidade?: number
  precoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  produto: Prisma.ProdutoCreateNestedOneWithoutItensCarrinhoInput
}

export type ItemCarrinhoUncheckedCreateWithoutCarrinhoInput = {
  id?: number
  produtoId: number
  quantidade?: number
  precoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemCarrinhoCreateOrConnectWithoutCarrinhoInput = {
  where: Prisma.ItemCarrinhoWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutCarrinhoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutCarrinhoInput>
}

export type ItemCarrinhoCreateManyCarrinhoInputEnvelope = {
  data: Prisma.ItemCarrinhoCreateManyCarrinhoInput | Prisma.ItemCarrinhoCreateManyCarrinhoInput[]
  skipDuplicates?: boolean
}

export type ItemCarrinhoUpsertWithWhereUniqueWithoutCarrinhoInput = {
  where: Prisma.ItemCarrinhoWhereUniqueInput
  update: Prisma.XOR<Prisma.ItemCarrinhoUpdateWithoutCarrinhoInput, Prisma.ItemCarrinhoUncheckedUpdateWithoutCarrinhoInput>
  create: Prisma.XOR<Prisma.ItemCarrinhoCreateWithoutCarrinhoInput, Prisma.ItemCarrinhoUncheckedCreateWithoutCarrinhoInput>
}

export type ItemCarrinhoUpdateWithWhereUniqueWithoutCarrinhoInput = {
  where: Prisma.ItemCarrinhoWhereUniqueInput
  data: Prisma.XOR<Prisma.ItemCarrinhoUpdateWithoutCarrinhoInput, Prisma.ItemCarrinhoUncheckedUpdateWithoutCarrinhoInput>
}

export type ItemCarrinhoUpdateManyWithWhereWithoutCarrinhoInput = {
  where: Prisma.ItemCarrinhoScalarWhereInput
  data: Prisma.XOR<Prisma.ItemCarrinhoUpdateManyMutationInput, Prisma.ItemCarrinhoUncheckedUpdateManyWithoutCarrinhoInput>
}

export type ItemCarrinhoCreateManyProdutoInput = {
  id?: number
  carrinhoId: number
  quantidade?: number
  precoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemCarrinhoUpdateWithoutProdutoInput = {
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  carrinho?: Prisma.CarrinhoUpdateOneRequiredWithoutItensNestedInput
}

export type ItemCarrinhoUncheckedUpdateWithoutProdutoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  carrinhoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemCarrinhoUncheckedUpdateManyWithoutProdutoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  carrinhoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemCarrinhoCreateManyCarrinhoInput = {
  id?: number
  produtoId: number
  quantidade?: number
  precoUnitario: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemCarrinhoUpdateWithoutCarrinhoInput = {
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  produto?: Prisma.ProdutoUpdateOneRequiredWithoutItensCarrinhoNestedInput
}

export type ItemCarrinhoUncheckedUpdateWithoutCarrinhoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  produtoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemCarrinhoUncheckedUpdateManyWithoutCarrinhoInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  produtoId?: Prisma.IntFieldUpdateOperationsInput | number
  quantidade?: Prisma.IntFieldUpdateOperationsInput | number
  precoUnitario?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ItemCarrinhoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  carrinhoId?: boolean
  produtoId?: boolean
  quantidade?: boolean
  precoUnitario?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  carrinho?: boolean | Prisma.CarrinhoDefaultArgs<ExtArgs>
  produto?: boolean | Prisma.ProdutoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itemCarrinho"]>

export type ItemCarrinhoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  carrinhoId?: boolean
  produtoId?: boolean
  quantidade?: boolean
  precoUnitario?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  carrinho?: boolean | Prisma.CarrinhoDefaultArgs<ExtArgs>
  produto?: boolean | Prisma.ProdutoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itemCarrinho"]>

export type ItemCarrinhoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  carrinhoId?: boolean
  produtoId?: boolean
  quantidade?: boolean
  precoUnitario?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  carrinho?: boolean | Prisma.CarrinhoDefaultArgs<ExtArgs>
  produto?: boolean | Prisma.ProdutoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itemCarrinho"]>

export type ItemCarrinhoSelectScalar = {
  id?: boolean
  carrinhoId?: boolean
  produtoId?: boolean
  quantidade?: boolean
  precoUnitario?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ItemCarrinhoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "carrinhoId" | "produtoId" | "quantidade" | "precoUnitario" | "createdAt" | "updatedAt", ExtArgs["result"]["itemCarrinho"]>
export type ItemCarrinhoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  carrinho?: boolean | Prisma.CarrinhoDefaultArgs<ExtArgs>
  produto?: boolean | Prisma.ProdutoDefaultArgs<ExtArgs>
}
export type ItemCarrinhoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  carrinho?: boolean | Prisma.CarrinhoDefaultArgs<ExtArgs>
  produto?: boolean | Prisma.ProdutoDefaultArgs<ExtArgs>
}
export type ItemCarrinhoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  carrinho?: boolean | Prisma.CarrinhoDefaultArgs<ExtArgs>
  produto?: boolean | Prisma.ProdutoDefaultArgs<ExtArgs>
}

export type $ItemCarrinhoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ItemCarrinho"
  objects: {
    carrinho: Prisma.$CarrinhoPayload<ExtArgs>
    produto: Prisma.$ProdutoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    carrinhoId: number
    produtoId: number
    quantidade: number
    precoUnitario: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["itemCarrinho"]>
  composites: {}
}

export type ItemCarrinhoGetPayload<S extends boolean | null | undefined | ItemCarrinhoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload, S>

export type ItemCarrinhoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ItemCarrinhoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ItemCarrinhoCountAggregateInputType | true
  }

export interface ItemCarrinhoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ItemCarrinho'], meta: { name: 'ItemCarrinho' } }
  /**
   * Find zero or one ItemCarrinho that matches the filter.
   * @param {ItemCarrinhoFindUniqueArgs} args - Arguments to find a ItemCarrinho
   * @example
   * // Get one ItemCarrinho
   * const itemCarrinho = await prisma.itemCarrinho.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ItemCarrinhoFindUniqueArgs>(args: Prisma.SelectSubset<T, ItemCarrinhoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ItemCarrinhoClient<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ItemCarrinho that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ItemCarrinhoFindUniqueOrThrowArgs} args - Arguments to find a ItemCarrinho
   * @example
   * // Get one ItemCarrinho
   * const itemCarrinho = await prisma.itemCarrinho.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ItemCarrinhoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ItemCarrinhoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItemCarrinhoClient<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ItemCarrinho that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemCarrinhoFindFirstArgs} args - Arguments to find a ItemCarrinho
   * @example
   * // Get one ItemCarrinho
   * const itemCarrinho = await prisma.itemCarrinho.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ItemCarrinhoFindFirstArgs>(args?: Prisma.SelectSubset<T, ItemCarrinhoFindFirstArgs<ExtArgs>>): Prisma.Prisma__ItemCarrinhoClient<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ItemCarrinho that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemCarrinhoFindFirstOrThrowArgs} args - Arguments to find a ItemCarrinho
   * @example
   * // Get one ItemCarrinho
   * const itemCarrinho = await prisma.itemCarrinho.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ItemCarrinhoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ItemCarrinhoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItemCarrinhoClient<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ItemCarrinhos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemCarrinhoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ItemCarrinhos
   * const itemCarrinhos = await prisma.itemCarrinho.findMany()
   * 
   * // Get first 10 ItemCarrinhos
   * const itemCarrinhos = await prisma.itemCarrinho.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const itemCarrinhoWithIdOnly = await prisma.itemCarrinho.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ItemCarrinhoFindManyArgs>(args?: Prisma.SelectSubset<T, ItemCarrinhoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ItemCarrinho.
   * @param {ItemCarrinhoCreateArgs} args - Arguments to create a ItemCarrinho.
   * @example
   * // Create one ItemCarrinho
   * const ItemCarrinho = await prisma.itemCarrinho.create({
   *   data: {
   *     // ... data to create a ItemCarrinho
   *   }
   * })
   * 
   */
  create<T extends ItemCarrinhoCreateArgs>(args: Prisma.SelectSubset<T, ItemCarrinhoCreateArgs<ExtArgs>>): Prisma.Prisma__ItemCarrinhoClient<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ItemCarrinhos.
   * @param {ItemCarrinhoCreateManyArgs} args - Arguments to create many ItemCarrinhos.
   * @example
   * // Create many ItemCarrinhos
   * const itemCarrinho = await prisma.itemCarrinho.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ItemCarrinhoCreateManyArgs>(args?: Prisma.SelectSubset<T, ItemCarrinhoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ItemCarrinhos and returns the data saved in the database.
   * @param {ItemCarrinhoCreateManyAndReturnArgs} args - Arguments to create many ItemCarrinhos.
   * @example
   * // Create many ItemCarrinhos
   * const itemCarrinho = await prisma.itemCarrinho.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ItemCarrinhos and only return the `id`
   * const itemCarrinhoWithIdOnly = await prisma.itemCarrinho.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ItemCarrinhoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ItemCarrinhoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ItemCarrinho.
   * @param {ItemCarrinhoDeleteArgs} args - Arguments to delete one ItemCarrinho.
   * @example
   * // Delete one ItemCarrinho
   * const ItemCarrinho = await prisma.itemCarrinho.delete({
   *   where: {
   *     // ... filter to delete one ItemCarrinho
   *   }
   * })
   * 
   */
  delete<T extends ItemCarrinhoDeleteArgs>(args: Prisma.SelectSubset<T, ItemCarrinhoDeleteArgs<ExtArgs>>): Prisma.Prisma__ItemCarrinhoClient<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ItemCarrinho.
   * @param {ItemCarrinhoUpdateArgs} args - Arguments to update one ItemCarrinho.
   * @example
   * // Update one ItemCarrinho
   * const itemCarrinho = await prisma.itemCarrinho.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ItemCarrinhoUpdateArgs>(args: Prisma.SelectSubset<T, ItemCarrinhoUpdateArgs<ExtArgs>>): Prisma.Prisma__ItemCarrinhoClient<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ItemCarrinhos.
   * @param {ItemCarrinhoDeleteManyArgs} args - Arguments to filter ItemCarrinhos to delete.
   * @example
   * // Delete a few ItemCarrinhos
   * const { count } = await prisma.itemCarrinho.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ItemCarrinhoDeleteManyArgs>(args?: Prisma.SelectSubset<T, ItemCarrinhoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ItemCarrinhos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemCarrinhoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ItemCarrinhos
   * const itemCarrinho = await prisma.itemCarrinho.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ItemCarrinhoUpdateManyArgs>(args: Prisma.SelectSubset<T, ItemCarrinhoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ItemCarrinhos and returns the data updated in the database.
   * @param {ItemCarrinhoUpdateManyAndReturnArgs} args - Arguments to update many ItemCarrinhos.
   * @example
   * // Update many ItemCarrinhos
   * const itemCarrinho = await prisma.itemCarrinho.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ItemCarrinhos and only return the `id`
   * const itemCarrinhoWithIdOnly = await prisma.itemCarrinho.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ItemCarrinhoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ItemCarrinhoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ItemCarrinho.
   * @param {ItemCarrinhoUpsertArgs} args - Arguments to update or create a ItemCarrinho.
   * @example
   * // Update or create a ItemCarrinho
   * const itemCarrinho = await prisma.itemCarrinho.upsert({
   *   create: {
   *     // ... data to create a ItemCarrinho
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ItemCarrinho we want to update
   *   }
   * })
   */
  upsert<T extends ItemCarrinhoUpsertArgs>(args: Prisma.SelectSubset<T, ItemCarrinhoUpsertArgs<ExtArgs>>): Prisma.Prisma__ItemCarrinhoClient<runtime.Types.Result.GetResult<Prisma.$ItemCarrinhoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ItemCarrinhos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemCarrinhoCountArgs} args - Arguments to filter ItemCarrinhos to count.
   * @example
   * // Count the number of ItemCarrinhos
   * const count = await prisma.itemCarrinho.count({
   *   where: {
   *     // ... the filter for the ItemCarrinhos we want to count
   *   }
   * })
  **/
  count<T extends ItemCarrinhoCountArgs>(
    args?: Prisma.Subset<T, ItemCarrinhoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ItemCarrinhoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ItemCarrinho.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemCarrinhoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ItemCarrinhoAggregateArgs>(args: Prisma.Subset<T, ItemCarrinhoAggregateArgs>): Prisma.PrismaPromise<GetItemCarrinhoAggregateType<T>>

  /**
   * Group by ItemCarrinho.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemCarrinhoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ItemCarrinhoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ItemCarrinhoGroupByArgs['orderBy'] }
      : { orderBy?: ItemCarrinhoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ItemCarrinhoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetItemCarrinhoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ItemCarrinho model
 */
readonly fields: ItemCarrinhoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ItemCarrinho.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ItemCarrinhoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  carrinho<T extends Prisma.CarrinhoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CarrinhoDefaultArgs<ExtArgs>>): Prisma.Prisma__CarrinhoClient<runtime.Types.Result.GetResult<Prisma.$CarrinhoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  produto<T extends Prisma.ProdutoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProdutoDefaultArgs<ExtArgs>>): Prisma.Prisma__ProdutoClient<runtime.Types.Result.GetResult<Prisma.$ProdutoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ItemCarrinho model
 */
export interface ItemCarrinhoFieldRefs {
  readonly id: Prisma.FieldRef<"ItemCarrinho", 'Int'>
  readonly carrinhoId: Prisma.FieldRef<"ItemCarrinho", 'Int'>
  readonly produtoId: Prisma.FieldRef<"ItemCarrinho", 'Int'>
  readonly quantidade: Prisma.FieldRef<"ItemCarrinho", 'Int'>
  readonly precoUnitario: Prisma.FieldRef<"ItemCarrinho", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"ItemCarrinho", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ItemCarrinho", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ItemCarrinho findUnique
 */
export type ItemCarrinhoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
  /**
   * Filter, which ItemCarrinho to fetch.
   */
  where: Prisma.ItemCarrinhoWhereUniqueInput
}

/**
 * ItemCarrinho findUniqueOrThrow
 */
export type ItemCarrinhoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
  /**
   * Filter, which ItemCarrinho to fetch.
   */
  where: Prisma.ItemCarrinhoWhereUniqueInput
}

/**
 * ItemCarrinho findFirst
 */
export type ItemCarrinhoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
  /**
   * Filter, which ItemCarrinho to fetch.
   */
  where?: Prisma.ItemCarrinhoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemCarrinhos to fetch.
   */
  orderBy?: Prisma.ItemCarrinhoOrderByWithRelationInput | Prisma.ItemCarrinhoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ItemCarrinhos.
   */
  cursor?: Prisma.ItemCarrinhoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemCarrinhos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemCarrinhos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemCarrinhos.
   */
  distinct?: Prisma.ItemCarrinhoScalarFieldEnum | Prisma.ItemCarrinhoScalarFieldEnum[]
}

/**
 * ItemCarrinho findFirstOrThrow
 */
export type ItemCarrinhoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
  /**
   * Filter, which ItemCarrinho to fetch.
   */
  where?: Prisma.ItemCarrinhoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemCarrinhos to fetch.
   */
  orderBy?: Prisma.ItemCarrinhoOrderByWithRelationInput | Prisma.ItemCarrinhoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ItemCarrinhos.
   */
  cursor?: Prisma.ItemCarrinhoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemCarrinhos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemCarrinhos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemCarrinhos.
   */
  distinct?: Prisma.ItemCarrinhoScalarFieldEnum | Prisma.ItemCarrinhoScalarFieldEnum[]
}

/**
 * ItemCarrinho findMany
 */
export type ItemCarrinhoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
  /**
   * Filter, which ItemCarrinhos to fetch.
   */
  where?: Prisma.ItemCarrinhoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemCarrinhos to fetch.
   */
  orderBy?: Prisma.ItemCarrinhoOrderByWithRelationInput | Prisma.ItemCarrinhoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ItemCarrinhos.
   */
  cursor?: Prisma.ItemCarrinhoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemCarrinhos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemCarrinhos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemCarrinhos.
   */
  distinct?: Prisma.ItemCarrinhoScalarFieldEnum | Prisma.ItemCarrinhoScalarFieldEnum[]
}

/**
 * ItemCarrinho create
 */
export type ItemCarrinhoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
  /**
   * The data needed to create a ItemCarrinho.
   */
  data: Prisma.XOR<Prisma.ItemCarrinhoCreateInput, Prisma.ItemCarrinhoUncheckedCreateInput>
}

/**
 * ItemCarrinho createMany
 */
export type ItemCarrinhoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ItemCarrinhos.
   */
  data: Prisma.ItemCarrinhoCreateManyInput | Prisma.ItemCarrinhoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ItemCarrinho createManyAndReturn
 */
export type ItemCarrinhoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * The data used to create many ItemCarrinhos.
   */
  data: Prisma.ItemCarrinhoCreateManyInput | Prisma.ItemCarrinhoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ItemCarrinho update
 */
export type ItemCarrinhoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
  /**
   * The data needed to update a ItemCarrinho.
   */
  data: Prisma.XOR<Prisma.ItemCarrinhoUpdateInput, Prisma.ItemCarrinhoUncheckedUpdateInput>
  /**
   * Choose, which ItemCarrinho to update.
   */
  where: Prisma.ItemCarrinhoWhereUniqueInput
}

/**
 * ItemCarrinho updateMany
 */
export type ItemCarrinhoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ItemCarrinhos.
   */
  data: Prisma.XOR<Prisma.ItemCarrinhoUpdateManyMutationInput, Prisma.ItemCarrinhoUncheckedUpdateManyInput>
  /**
   * Filter which ItemCarrinhos to update
   */
  where?: Prisma.ItemCarrinhoWhereInput
  /**
   * Limit how many ItemCarrinhos to update.
   */
  limit?: number
}

/**
 * ItemCarrinho updateManyAndReturn
 */
export type ItemCarrinhoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * The data used to update ItemCarrinhos.
   */
  data: Prisma.XOR<Prisma.ItemCarrinhoUpdateManyMutationInput, Prisma.ItemCarrinhoUncheckedUpdateManyInput>
  /**
   * Filter which ItemCarrinhos to update
   */
  where?: Prisma.ItemCarrinhoWhereInput
  /**
   * Limit how many ItemCarrinhos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ItemCarrinho upsert
 */
export type ItemCarrinhoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
  /**
   * The filter to search for the ItemCarrinho to update in case it exists.
   */
  where: Prisma.ItemCarrinhoWhereUniqueInput
  /**
   * In case the ItemCarrinho found by the `where` argument doesn't exist, create a new ItemCarrinho with this data.
   */
  create: Prisma.XOR<Prisma.ItemCarrinhoCreateInput, Prisma.ItemCarrinhoUncheckedCreateInput>
  /**
   * In case the ItemCarrinho was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ItemCarrinhoUpdateInput, Prisma.ItemCarrinhoUncheckedUpdateInput>
}

/**
 * ItemCarrinho delete
 */
export type ItemCarrinhoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
  /**
   * Filter which ItemCarrinho to delete.
   */
  where: Prisma.ItemCarrinhoWhereUniqueInput
}

/**
 * ItemCarrinho deleteMany
 */
export type ItemCarrinhoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ItemCarrinhos to delete
   */
  where?: Prisma.ItemCarrinhoWhereInput
  /**
   * Limit how many ItemCarrinhos to delete.
   */
  limit?: number
}

/**
 * ItemCarrinho without action
 */
export type ItemCarrinhoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemCarrinho
   */
  select?: Prisma.ItemCarrinhoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemCarrinho
   */
  omit?: Prisma.ItemCarrinhoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemCarrinhoInclude<ExtArgs> | null
}
